### ISSUE TITLE
Extension not compatible with fal_securedownload

### ISSUE THREAD

**Issue by christophlehmann** [cabservicesag/falsearch#1]
TYPO3 6.2.19
falsearch 0.0.6
fal_securedownloads 1.0.0

PHP Catchable fatal error:  Argument 3 passed to BeechIt\FalSecuredownload\Aspects\PublicUrlAspect::generatePublicUrl() must implement interface TYPO3\CMS\Core\Resource\FileInterface, instance of Cabag\Falsearch\Xclass\Folder given in .../typo3conf/ext/fal_securedownload/Classes/Aspects/PublicUrlAspect.php on line 73, referer: ...

It would be nice when they work together

**Comment by CDRO** [comment]
Hello Christoph,

I'll check this issue this week and try to work out a fix by the end of the week.

**Comment by CDRO** [comment]
I'll have to disappoint you about the deadline, I think I wont be able to hold it. I'm going at it asap but you know how it is.

**Comment by CDRO** [comment]
@christophlehmann This should now have been solved in the newest version of fal_securedownloads.

Also there is a new version of falsearch available for download right now.

Thanks for your feedback.

**Comment by christophlehmann** [comment]
@CDRO Thanks for your investigation, but it doesn't work with falsearch 0.1.3 and fal_securedownloads 1.0.2

I get 

`PHP Catchable fatal error:  Argument 3 passed to BeechIt\\FalSecuredownload\\Aspects\\PublicUrlAspect::generatePublicUrl() must implement interface TYPO3\\CMS\\Core\\Resource\\FileInterface, instance of Cabag\\Falsearch\\Xclass\\Folder given in .../fal_securedownload/Classes/Aspects/PublicUrlAspect.php on line 79`

I will try to have a look at it later

**Comment by christophlehmann** [comment]
Now I tried the current git version 1.0.3-dev of fal_securedownload and it works like a charm. Thank you!
